version: "3.10"
services:
  server:
    build: .
    restart: on-failure
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    env_file: .env
    volumes:
      - .:/backend
      - static_volume:/backend/frontend/static

    depends_on:
      - database

  database:
    image: postgres:12.0-alpine
    env_file: .env

  redis_database:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/backend/frontend/static

    ports:
      - 80:80

    depends_on:
      - server

volumes:
  static_volume:
