version: "3.10"
services:
  server:
    build: .
    restart: on-failure
    entrypoint: /run.sh
    env_file: .env
    volumes:
      - .:/backend
      - static_volume:/backend/frontend/static
      - media_volume:/backend/frontend/media

    depends_on:
      - database

    networks:
      - hireme

  database:
    image: postgres:12.0-alpine
    env_file: .env
    networks:
      - hireme

  redis_database:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

    networks:
      - hireme

volumes:
  static_volume:
  media_volume:

networks:
  hireme:
    name: hireme
    driver: bridge
    external: true
