# Generated by Django 4.1.7 on 2023-03-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(null=True, upload_to="%Y/%M/%d/%h")),
                ("occupation", models.CharField(max_length=255, null=True)),
                ("about_company", models.TextField(null=True)),
                ("company_website", models.URLField()),
                ("location", models.CharField(max_length=255)),
                ("employer", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="company.company",
                    ),
                ),
            ],
        ),
    ]
