# Generated by Django 4.1.7 on 2023-03-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_type", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Company Type",
                "verbose_name_plural": "Company Types",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="companyvalue",
            options={
                "verbose_name": "Company Value",
                "verbose_name_plural": "Company Values",
            },
        ),
        migrations.RenameField(
            model_name="company",
            old_name="employer",
            new_name="employers_number",
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.ManyToManyField(to="company.companytype"),
        ),
    ]
