# Generated by Django 4.1.7 on 2023-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.AddField(
            model_name="company",
            name="employer",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="about_company",
            field=models.TextField(null=True),
        ),
    ]
