# Generated by Django 4.1.7 on 2023-03-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userambitions_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userambitions',
            name='stacks',
            field=models.ManyToManyField(to='user.stack'),
        ),
        migrations.AlterField(
            model_name='userworkexperience',
            name='stacks',
            field=models.ManyToManyField(to='user.stack'),
        ),
    ]
