# Generated by Django 4.1.7 on 2023-04-11 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_is_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_sales",
        ),
    ]
