# Generated by Django 4.1.7 on 2023-03-10 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userambitions_stacks_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserAmbitions",
            new_name="UserAmbition",
        ),
    ]
