# Generated by Django 4.1.7 on 2023-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_user_is_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(default=1, verbose_name="описание"),
            preserve_default=False,
        ),
    ]
