# Generated by Django 4.1.7 on 2023-03-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_userambitions_userambition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userambition",
            old_name="experience_companies",
            new_name="about_myself",
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(default="", upload_to="%Y/%M/%d/$H/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userambition",
            name="achievement",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userambition",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ambition",
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name="WorkExpectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_type", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_expectations",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
