# Generated by Django 4.1.7 on 2023-04-25 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
    ]
