# Generated by Django 4.1.7 on 2023-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_rename_experience_companies_userambition_about_myself_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexpectation",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="work_expectations",
            field=models.ManyToManyField(to="user.workexpectation"),
        ),
    ]
