# Generated by Django 4.1.7 on 2023-03-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_remove_workexpectation_user_user_work_expectations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userambition",
            name="stacks",
        ),
        migrations.AddField(
            model_name="user",
            name="stacks",
            field=models.ManyToManyField(to="user.stack"),
        ),
        migrations.AlterField(
            model_name="userworkexperience",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worked_companies",
                to="user.user",
            ),
        ),
    ]
