# Generated by Django 4.1.7 on 2023-03-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_remove_userambition_stacks_user_stacks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
