# Generated by Django 4.1.7 on 2023-03-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
