# Generated by Django 4.1.7 on 2023-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_company_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(null=True, upload_to="%Y/%M/%d/%h"),
        ),
    ]
