# Generated by Django 4.1.7 on 2023-03-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                ("from_salary", models.IntegerField(default=0)),
                ("to_salary", models.IntegerField(blank=True, null=True)),
                ("from_experience", models.IntegerField(default=0)),
                ("to_experience", models.IntegerField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "responsibility",
                    models.CharField(max_length=255, verbose_name="responsibilities"),
                ),
                ("expectation", models.CharField(max_length=255)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_type", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Stack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="JobBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefit", models.CharField(max_length=255)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_benefits",
                        to="job.job",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="job_stack",
            field=models.ManyToManyField(related_name="stacks", to="job.stack"),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.ManyToManyField(related_name="types", to="job.jobtype"),
        ),
        migrations.AddField(
            model_name="job",
            name="soft_skill",
            field=models.ManyToManyField(related_name="job", to="job.stack"),
        ),
        migrations.AddField(
            model_name="job",
            name="will_be_plus",
            field=models.ManyToManyField(related_name="will_be_plus", to="job.stack"),
        ),
    ]
