# Generated by Django 4.1.7 on 2023-03-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_remove_company_email_company_employer_and_more"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vacancies",
                to="company.company",
            ),
        ),
    ]
