# Generated by Django 4.1.7 on 2023-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="soft_skill",
            field=models.ManyToManyField(related_name="job", to="job.jobstack"),
        ),
        migrations.AddField(
            model_name="job",
            name="will_be_plus",
            field=models.ManyToManyField(
                related_name="will_be_plus", to="job.jobstack"
            ),
        ),
    ]
